### PR TITLE
Support "constraints" with patch extends and other minor changes

### PR DESCRIPTION
**Pull request by rmouritzen-splunk**
Support `constraints` with patch extends

Fix bug in validator2 where it incorrectly tries to return a compile regex instead of the original regex string, resulting in a JSON encoding error.

Fix runtime warning when loading dictionary page: change `conn.params()` to `conn.params` (use of parenthesis with map fields is deprecated).

Update Docker Elixir image to 1.17.2.

Minor dependency update: Jason library updated to 1.4.4.

Bump version to 2.72.0.

### CODE REVIEW

**Review by floydtree — APPROVED** [review]

**Comment by floydtree** [comment]
Thanks for this Rick! 

A side note, now that we have a functioning regex based validation of attribute values, I think we need to revisit the regex patterns that we have in our dict and ensure those are all accurate and agreeable by consumers. Especially, for the controversial attributes like timestamp strings, (e.g. is "T" a required separator or no?) 

@pagbabian-splunk @mikeradka @zschmerber

**Review by query-jeremy — COMMENTED** [review]
LGTM

**Comment by query-jeremy** [comment]
> Thanks for this Rick!
> 
> A side note, now that we have a functioning regex based validation of attribute values, I think we need to revisit the regex patterns that we have in our dict and ensure those are all accurate and agreeable by consumers. Especially, for the controversial attributes like timestamp strings, (e.g. is "T" a required separator or no?)

And `email_t`. Validating email addresses with regular expressions is usually a [bad idea](https://stackoverflow.com/questions/201323/how-can-i-validate-an-email-address-using-a-regular-expression).

**Comment by pagbabian-splunk** [comment]
We also have `url_t` without a regex validator. Also a bad idea?

**Comment by mikeradka** [comment]
Something to add to the conversation here - detection engineering often relies just as much on non-standard values for fields as it does for standard values for fields. Often, non-standard values in a field that is supposed to have a standard value can be detected as a noteworthy anomaly. A good example of this with a URL would be a URL field in a log that contains commands, which can indicate a [command-line injection](https://owasp.org/www-community/attacks/Command_Injection) technique by an attacker. [Shellshock](https://securityintelligence.com/articles/shellshock-vulnerability-in-depth/) is one old example of this.

**Comment by rmouritzen-splunk** [comment]
Mike's comment (@mikeradka) suggests we should either remove some or all of the regex constraints, or change the regex pattern to a recommendation for some or all of the usages.

**Comment by pagbabian-splunk** [comment]
This will require a lot of discussion - I understand the use case, but we should then consider a `url_string` value with the URL object of `url_t` type.  Removing all constraints is a non-starter for me.

**Comment by rmouritzen-splunk** [comment]
Agree. So then we'll need to decide if the constraints ought to be strictly enforced (validation errors) or recommendations (validation warnings), some mix, or perhaps relax the regex constraints themselves, changing the regex patterns in a backwards compatible way to allow additional variations.

**Pull request merged**
